# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tf_na_vector <- function(length) {
    .Call(`_GCAMCTF_na_vector`, length)
}

tf_delta <- function(x) {
    .Call(`_GCAMCTF_delta`, x)
}

tf_rank <- function(x) {
    .Call(`_GCAMCTF_rank`, x)
}

tf_sum <- function(x) {
    .Call(`_GCAMCTF_sum`, x)
}

tf_mean <- function(x) {
    .Call(`_GCAMCTF_mean`, x)
}

tf_stdev <- function(x) {
    .Call(`_GCAMCTF_stdev`, x)
}

tf_tsmin <- function(x) {
    .Call(`_GCAMCTF_tsmin`, x)
}

tf_tsmax <- function(x) {
    .Call(`_GCAMCTF_tsmax`, x)
}

tf_tsrank <- function(x) {
    .Call(`_GCAMCTF_tsrank`, x)
}

tf_covariance <- function(x, y) {
    .Call(`_GCAMCTF_covariance`, x, y)
}

tf_corr <- function(x, y) {
    .Call(`_GCAMCTF_corr`, x, y)
}

tf_sign <- function(x) {
    .Call(`_GCAMCTF_sign`, x)
}

tf_sma <- function(x, m) {
    .Call(`_GCAMCTF_sma`, x, m)
}

tf_wma <- function(x) {
    .Call(`_GCAMCTF_wma`, x)
}

tf_decaylinear <- function(x) {
    .Call(`_GCAMCTF_decaylinear`, x)
}

tf_sequence <- function(n) {
    .Call(`_GCAMCTF_sequence`, n)
}

tf_sumac <- function(x) {
    .Call(`_GCAMCTF_sumac`, x)
}

tf_log <- function(x) {
    .Call(`_GCAMCTF_log`, x)
}

tf_abs <- function(x) {
    .Call(`_GCAMCTF_abs`, x)
}

tf_prod <- function(x) {
    .Call(`_GCAMCTF_prod`, x)
}

tf_count <- function(x) {
    .Call(`_GCAMCTF_count`, x)
}

tf_regbeta <- function(y, x) {
    .Call(`_GCAMCTF_regbeta`, y, x)
}

tf_regresi <- function(y, x) {
    .Call(`_GCAMCTF_regresi`, y, x)
}

tf_filter <- function(x, cond) {
    .Call(`_GCAMCTF_filter`, x, cond)
}

tf_highday <- function(x) {
    .Call(`_GCAMCTF_highday`, x)
}

tf_lowday <- function(x) {
    .Call(`_GCAMCTF_lowday`, x)
}

tf_assert_valid_from_to <- function(from_to) {
    invisible(.Call(`_GCAMCTF_assert_valid`, from_to))
}

tf_any_na <- function(x) {
    .Call(`_GCAMCTF_any_na`, x)
}

tf_assert_no_na <- function(x) {
    invisible(.Call(`_GCAMCTF_assert_no_na`, x))
}

tf_assert_valid_dates <- function(x, field) {
    invisible(.Call(`_GCAMCTF_assert_valid_dates`, x, field))
}

tf_assert_valid_price <- function(x, field) {
    invisible(.Call(`_GCAMCTF_assert_valid_price`, x, field))
}

tf_assert_valid_volume <- function(x, field) {
    invisible(.Call(`_GCAMCTF_assert_valid_volume`, x, field))
}

tf_assert_is_sorted <- function(x) {
    invisible(.Call(`_GCAMCTF_assert_sorted`, x))
}

tf_qt_tdates <- function(quote_ptr, from_to) {
    .Call(`_GCAMCTF_tf_qt_tdates`, quote_ptr, from_to)
}

tf_qt_today <- function(quote_ptr, today) {
    .Call(`_GCAMCTF_tf_qt_today`, quote_ptr, today)
}

tf_qt_get <- function(quote_ptr, today, tag, delay) {
    .Call(`_GCAMCTF_tf_qt_get`, quote_ptr, today, tag, delay)
}

tf_qt_ts_get <- function(quote_ptr, today, tag, n, delay) {
    .Call(`_GCAMCTF_tf_qt_ts_get`, quote_ptr, today, tag, n, delay)
}

tf_ts_op <- function(x, y, op) {
    .Call(`_GCAMCTF_tf_ts_op`, x, y, op)
}

tf_ts_scalar_op <- function(x, y, op) {
    .Call(`_GCAMCTF_tf_ts_scalar_op`, x, y, op)
}

tf_ts <- function(quote_ptr, today, n) {
    .Call(`_GCAMCTF_tf_ts`, quote_ptr, today, n)
}

tf_assert_valid_panel <- function(x) {
    invisible(.Call(`_GCAMCTF_tf_assert_valid_panel`, x))
}

tf_panel_sum <- function(x) {
    .Call(`_GCAMCTF_tf_panel_sum`, x)
}

tf_assert_same_size <- function(x, y) {
    invisible(.Call(`_GCAMCTF_tf_assert_same_size`, x, y))
}

create_xts <- function(x_mat, x_dates) {
    .Call(`_GCAMCTF_create_xts`, x_mat, x_dates)
}

#' The registered factor names
#'
#' Return all the factor names that are registered in the C++ routine.
#'
#' @export
tf_reg_factors <- function() {
    .Call(`_GCAMCTF_tf_reg_factors`)
}

#' The quote external pointer
#'
#' @param qt_tbl A `data.frame` contains the daily price info
#'   of a security. It must contain a column `DATE` and 10 numeric
#'   columns `PCLOSE`, `OPEN`, `HIGH`, `LOW`, `CLOSE`, `VWAP`,
#'   `VOLUME`, `AMOUNT`, `BMK_CLOSE`, `BMK_OPEN`. Moreover, the
#'   column `DATE` must be in ascending order.
#'
#' @return An R external pointer than can hold a `Quote` object.
#' @export
tf_quote_xptr <- function(qt_tbl) {
    .Call(`_GCAMCTF_tf_quote_xptr`, qt_tbl)
}

tf_enc2utf8 <- function(x, only_mark = FALSE) {
    .Call(`_GCAMCTF_enc2utf8`, x, only_mark)
}

#' @rdname tf_quote_xptr
#' @export
tf_quotes_xptr <- function(qt_tbls) {
    .Call(`_GCAMCTF_tf_quotes_xptr`, qt_tbls)
}

tf_assert_class <- function(x, classname) {
    invisible(.Call(`_GCAMCTF_asset_valid`, x, classname))
}

#' Calculate the TF for single security
#'
#' @param qt_ptr An R external pointer generated by [tf_quote_xptr()].
#' @param names A character vector in which all the elements are registered.
#' @param from_to A length two `Date` vector whose first element must be
#'   smaller than or equal to the first.
#'
#' @return An `xts` object in which the columns are the factors' value.
#' @export
tf_qt_cal <- function(qt_ptr, names, from_to) {
    .Call(`_GCAMCTF_tf_qt_cal`, qt_ptr, names, from_to)
}

#' Calculate the TF for a security pool
#'
#' @param qts_ptr An R external pointer generated by [tf_quotes_xptr()].
#' @param name a registered factor name
#' @inheritParams tf_qt_cal
#' @return An `xts` object in which the columns are the factor value for
#'   each security in the pool.
#' @export
tf_qts_cal <- function(qts_ptr, name, from_to) {
    .Call(`_GCAMCTF_tf_qts_cal`, qts_ptr, name, from_to)
}

