# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tf_na_vector <- function(length) {
    .Call(`_GCAMCTF_na_vector`, length)
}

tf_delta <- function(x, n) {
    .Call(`_GCAMCTF_delta`, x, n)
}

tf_rank <- function(x) {
    .Call(`_GCAMCTF_rank`, x)
}

tf_sum <- function(x) {
    .Call(`_GCAMCTF_sum`, x)
}

tf_mean <- function(x) {
    .Call(`_GCAMCTF_mean`, x)
}

tf_stdev <- function(x) {
    .Call(`_GCAMCTF_stdev`, x)
}

tf_tsmin <- function(x) {
    .Call(`_GCAMCTF_tsmin`, x)
}

tf_tsmax <- function(x) {
    .Call(`_GCAMCTF_tsmax`, x)
}

tf_tsrank <- function(x) {
    .Call(`_GCAMCTF_tsrank`, x)
}

tf_covariance <- function(x, y) {
    .Call(`_GCAMCTF_covariance`, x, y)
}

tf_corr <- function(x, y) {
    .Call(`_GCAMCTF_corr`, x, y)
}

tf_sign <- function(x) {
    .Call(`_GCAMCTF_sign`, x)
}

tf_sma <- function(x, m) {
    .Call(`_GCAMCTF_sma`, x, m)
}

tf_wma <- function(x) {
    .Call(`_GCAMCTF_wma`, x)
}

tf_decaylinear <- function(x) {
    .Call(`_GCAMCTF_decaylinear`, x)
}

tf_sequence <- function(n) {
    .Call(`_GCAMCTF_sequence`, n)
}

tf_sumac <- function(x) {
    .Call(`_GCAMCTF_sumac`, x)
}

tf_log <- function(x) {
    .Call(`_GCAMCTF_log`, x)
}

tf_abs <- function(x) {
    .Call(`_GCAMCTF_abs`, x)
}

tf_prod <- function(x) {
    .Call(`_GCAMCTF_prod`, x)
}

tf_count <- function(x) {
    .Call(`_GCAMCTF_count`, x)
}

tf_regbeta <- function(y, x) {
    .Call(`_GCAMCTF_regbeta`, y, x)
}

tf_regresi <- function(y, x) {
    .Call(`_GCAMCTF_regresi`, y, x)
}

tf_filter <- function(x, cond) {
    .Call(`_GCAMCTF_filter`, x, cond)
}

tf_highday <- function(x) {
    .Call(`_GCAMCTF_highday`, x)
}

tf_lowday <- function(x) {
    .Call(`_GCAMCTF_lowday`, x)
}

tf_assert_valid_from_to <- function(from_to) {
    invisible(.Call(`_GCAMCTF_assert_valid`, from_to))
}

tf_assert_same_size <- function(x, y) {
    invisible(.Call(`_GCAMCTF_assert_same_size`, x, y))
}

tf_any_na <- function(x) {
    .Call(`_GCAMCTF_any_na`, x)
}

tf_assert_no_na <- function(x) {
    invisible(.Call(`_GCAMCTF_assert_no_na`, x))
}

tf_assert_is_sorted <- function(x) {
    invisible(.Call(`_GCAMCTF_assert_sorted`, x))
}

test_qt_tdates <- function(quotes_ptr, from_to) {
    .Call(`_GCAMCTF_test_qt_tdates`, quotes_ptr, from_to)
}

test_qt_today <- function(quotes_ptr, today) {
    .Call(`_GCAMCTF_test_qt_today`, quotes_ptr, today)
}

test_qt_get <- function(quotes_ptr, today, tag, delay) {
    .Call(`_GCAMCTF_test_qt_get`, quotes_ptr, today, tag, delay)
}

test_qt_ts_get <- function(quotes_ptr, today, tag, n, delay) {
    .Call(`_GCAMCTF_test_qt_ts_get`, quotes_ptr, today, tag, n, delay)
}

test_ts_op <- function(x, y, op) {
    .Call(`_GCAMCTF_test_ts_op`, x, y, op)
}

test_ts_scalar_op <- function(x, y, op) {
    .Call(`_GCAMCTF_test_ts_scalar_op`, x, y, op)
}

#' The registered factor names
#'
#' Return all the factor names that are registered in the C++ routine.
#'
#' @export
tf_reg_factors <- function() {
    .Call(`_GCAMCTF_tf_reg_factors`)
}

#' The quotes external pointer
#'
#' @param qt_tbl A `data.frame` contains the daily price info
#'   of a security. It must contain a column `DATE` and 10 numeric
#'   columns `PCLOSE`, `OPEN`, `HIGH`, `LOW`, `CLOSE`, `VWAP`,
#'   `VOLUME`, `AMOUNT`, `BMK_CLOSE`, `BMK_OPEN`. Moreover, the
#'   column `DATE` must be in ascending order.
#'
#' @return An R external pointer than can hold a `Quotes` object.
#' @export
tf_quotes_xptr <- function(qt_tbl) {
    .Call(`_GCAMCTF_tf_quotes_xptr`, qt_tbl)
}

#' Calculate the technical factor (TF)
#'
#' @param qt_ptr An R external pointer generated by [tf_quotes_xptr()].
#' @param name A registered factor name.
#' @param from_to A length two `Date` vector whose first element must be
#'   smaller than or equal to the first.
#'
#' @return A `data.frame` with two columns `DATE` and `VALUE` . The order
#'   of column `DATE` must be in ascending order.
#' @export
tf_cal <- function(qt_ptr, name, from_to) {
    .Call(`_GCAMCTF_tf_cal`, qt_ptr, name, from_to)
}

